import { describe, expect, it } from 'vitest';
import path from 'node:path';
import {
  assertNonDegenerate,
  describeValueSurfaceDrift,
  deriveValueSurface,
  DIST_DIR,
  GOLDEN_PATH,
  kindOf,
  MIN_VALUE_EXPORTS,
  PACKAGE_NAME,
  readGoldenDocument,
  REGENERATE_COMMAND,
  toGoldenDocument,
} from '../scripts/value-surface.mjs';

/**
 * The root barrel's public RUNTIME (value) surface, pinned against the built barrel.
 *
 * `coreBarrelTypeSurface.spec.ts` pins the TYPE half — which names an embedder can write in a type
 * position. This file pins the other half: which names actually exist as values when an embedder
 * imports the package and calls, constructs or reads them. They are emitted by different halves of
 * the compiler into different files, and **nothing that guards one guards the other**.
 *
 * ## The hole this closes, measured rather than argued
 *
 * The type pin's own boundary list records that a value export becoming type-only is invisible to
 * it. That is correct for a type-surface pin and is not a defect in it — but until this file
 * existed, nothing else covered the value half either, so it was unguarded rather than guarded
 * elsewhere.
 *
 * The measurement: rewriting one line of `src/index.ts` from
 * `export * from '#src/history/historyStore.js'` to `export type * from …` and rebuilding leaves
 * the emitted declarations identical in surface — the same 238 exports, the same three classes —
 * while `dist/index.js` silently drops five runtime exports, `HistoryStore` among them. Every cell
 * of the type-surface spec passes. An embedder's `new HistoryStore(...)` stops existing. That is
 * the whole reason for this file, and it is the control mutation the node was accepted against.
 *
 * ## Why this is a separate file rather than more cells in the type spec
 *
 * Different oracle, different artifact, different failure. The type pin spawns `tsc` over
 * `dist/*.d.ts` and reads its exit status; this one imports `dist/index.js` and reads what came
 * back. A reader looking at a red cell should not have to work out which half of the compiler it
 * is about, and the type spec's docblock is a single sustained argument about types that a runtime
 * half would dilute.
 *
 * ## Where the expectation comes from
 *
 * **A committed golden, `coreBarrelValueSurface.golden.json`, plus one derived cross-check.**
 *
 * The type pin can do something this one cannot: it DERIVES what ought to be exported from an
 * independent source — the type-reference graph of the emitted declarations — so its expectation is
 * not a restatement of the barrel. No such invariant exists for values. Nothing in this repository
 * says which runtime values *ought* to be public; the barrel is the only statement of that. A
 * derived expectation here would read the barrel to decide what the barrel should contain, and
 * would agree with it always.
 *
 * So the golden is honestly what it is: a **change detector** over the built artifact, generated by
 * `pnpm --filter @gaunt-sloth/core run value-surface:generate`, committed, and reviewed by a human
 * when it moves — the same contract `coreBarrelTypeSurface.golden.json` and
 * `schema/gsloth-config.schema.json` already keep in this package. It cannot stop someone
 * regenerating a loss away; what it converts is the failure mode, from silence into a diff that
 * names the vanished exports, in a commit, for a reviewer.
 *
 * **The cross-check is the one cell whose expectation is genuinely independent.** A class is both a
 * type and a value, so every name the emitted DECLARATIONS call a class must also arrive as a
 * runtime class. Those two facts are written by different emitters into different files, so the
 * cell can fail — and on the `export type *` mutation above, it is what fires first and by name.
 *
 * ## What is pinned, and what is deliberately not
 *
 * Name and kind. `kind` separates `class` from `function` by the language's own semantics (a class
 * constructor's `prototype` is non-writable), and keeps an object's internal tag, so `array` and
 * `regexp` do not flatten into `object`.
 *
 * Not pinned: function arity, object key sets, class member lists. Those are SHAPE, and an
 * embedder's own compiler checks them against the shipped declarations — pinning them here would
 * churn the golden on internal refactors while adding nothing the type surface does not hold.
 * Not pinned either: values. A constant's contents change for ordinary reasons and are not surface.
 *
 * ## What this pin does NOT catch — stated because the temptation is to overstate it
 *
 * - **A loss regenerated away.** As above: the golden makes it loud, not impossible.
 * - **A deliberate narrowing.** Deleting an `export *` removes the names from the barrel and from
 *   the golden's next regeneration alike. What it cannot be is silent.
 * - **A behaviour change behind an unchanged name and kind.** A function that still exists and
 *   still returns the wrong thing is every other spec's job, not this one's.
 * - **Anything about the six other workspace packages.** This pins `@gaunt-sloth/core` only.
 *
 * It needs `dist/` to exist. `pnpm test` builds first — including both CI unit jobs — and a bare
 * `pnpm run unit` on a never-built tree fails here with a message naming the missing artifact
 * rather than with a resolution error. It reads whatever `dist/` holds: on a tree built before an
 * edit to `src/`, this checks the older barrel, which is the first thing to rule out when the
 * golden reports a loss.
 */

describe('@gaunt-sloth/core root barrel runtime surface', () => {
  it('matches the committed golden, name for name and kind for kind', async () => {
    // The primary guard. `describeValueSurfaceDrift` is what turns the situations an equality
    // failure conflates — an export vanished, an export added, a name still here but a different
    // kind — into different sentences with different advice; the drift cells below pin that
    // wording, because a message nobody ever reads is a message nobody notices going wrong.
    const derived = toGoldenDocument(await deriveValueSurface());
    const committed = readGoldenDocument();

    // The drift report is the received value rather than the message, so it is printed once and
    // names every export that moved: the message says which file disagrees, the report says how.
    const drift = describeValueSurfaceDrift(committed, derived);
    expect(
      drift,
      `the committed golden ${GOLDEN_PATH} no longer describes the runtime surface`
    ).toBeNull();

    // The drift report reads the export lists. This says the file as a whole is what the generator
    // writes, so a hand-edit anywhere in it — including to the header that tells the next reader
    // how to regenerate — is a failure rather than a silent divergence.
    expect(
      committed,
      `${GOLDEN_PATH} is not what the generator writes: ${REGENERATE_COMMAND}`
    ).toEqual(derived);
  });

  it('reaches the built barrel by resolving the package name, as an embedder does', async () => {
    // Resolution by SELF-REFERENCE through the package `exports` map — not a relative path into
    // dist/. A break in that map, or a map pointed at something that is not the built barrel, reds
    // nothing else in this repository, where every module is reachable by its own path.
    //
    // Compared through `path.relative`, never by string prefix. The two sides are built by
    // different machinery — `DIST_DIR` from `fileURLToPath` + `path.join`, `entry` from Node's
    // resolver — and a prefix test on paths that disagree about separators is the exact shape of
    // the recurring win32-only false red. `path.relative` resolves both sides first, so it is
    // separator-agnostic, and pinning the whole relative path also says WHICH file resolved
    // rather than merely that it sat somewhere under dist/.
    const { entry } = await deriveValueSurface();
    expect(
      path.relative(DIST_DIR, entry),
      `${PACKAGE_NAME} did not resolve to the built barrel: ${entry}`
    ).toBe('index.js');
  });

  it('hands out every class the declarations name, as a runtime class', async () => {
    // The one cell here whose expectation does not come from the artifact under test. A class is
    // both a type and a value; the declarations say which names are classes, the emitted
    // JavaScript says which names are values, and the two are written by different emitters. This
    // is what fires, by name, when an `export *` becomes an `export type *`.
    const { exports, declaredClasses } = await deriveValueSurface();
    const runtime = new Map(exports.map((entry) => [entry.name, entry.kind]));

    // Without this the cell would pass vacuously if the oracle ever returned nothing.
    expect(
      declaredClasses.length,
      'the declarations name no classes at all — the cross-check oracle has collapsed and this cell is asserting nothing'
    ).toBeGreaterThan(0);

    const missing = declaredClasses.filter((name) => !runtime.has(name));
    expect(
      missing,
      `these are classes in ${PACKAGE_NAME}'s declarations but are NOT runtime exports of its barrel, so an embedder can name the type and cannot construct it — the usual cause is an "export *" written as "export type *" in src/index.ts`
    ).toEqual([]);

    const demoted = declaredClasses
      .filter((name) => runtime.has(name))
      .filter((name) => runtime.get(name) !== 'class')
      .map((name) => `${name} (${runtime.get(name)})`);
    expect(
      demoted,
      'these are classes in the declarations but arrive at runtime as something else'
    ).toEqual([]);
  });

  it('refuses a degenerate derivation, and rejects each shape one can take', async () => {
    // `deriveValueSurface` has already run this on the real surface — reaching this line at all is
    // the positive half. The rest is the half that matters: a guard nothing ever fails is a guard
    // nobody can trust, so each degenerate shape is fed in by hand and must be named in the throw.
    const real = await deriveValueSurface();

    expect(() => assertNonDegenerate({ ...real, entry: '/elsewhere/index.js' })).toThrow(
      /outside .* the probe is not reading the built barrel/s
    );
    expect(() => assertNonDegenerate({ ...real, exports: real.exports.slice(0, 3) })).toThrow(
      /found only 3 runtime exports, below the floor/
    );

    // The failure a name-set check cannot see, and the reason the kind classifier has a guard of
    // its own: a `kindOf` that answered "object" for everything would write a self-consistent
    // golden, compare clean forever, and never report a class demoted to a plain object.
    const collapsed = real.exports.map((entry) => ({ ...entry, kind: 'object' }));
    expect(collapsed.length).toBeGreaterThanOrEqual(MIN_VALUE_EXPORTS);
    expect(() => assertNonDegenerate({ ...real, exports: collapsed })).toThrow(
      /classified no export as class, function, string/
    );
  });

  it('distinguishes the kinds it claims to distinguish', () => {
    // Direct cells over hand-constructed values. The golden is written BY this function, so it
    // cannot disagree with it — only these lines can say the classifier is right.
    class Klass {}
    expect(kindOf(Klass)).toBe('class');
    expect(kindOf(class extends Klass {})).toBe('class');
    expect(kindOf(function named() {})).toBe('function');
    expect(kindOf(() => undefined)).toBe('function');
    expect(kindOf([])).toBe('array');
    expect(kindOf(/pattern/)).toBe('regexp');
    expect(kindOf(new Map())).toBe('map');
    expect(kindOf({})).toBe('object');
    expect(kindOf(null)).toBe('null');
    expect(kindOf(undefined)).toBe('undefined');
    expect(kindOf('text')).toBe('string');
    expect(kindOf(1)).toBe('number');
    expect(kindOf(true)).toBe('boolean');

    // The discriminating pair: a class and a plain function are both `typeof 'function'`, and the
    // whole kind field is worthless if these two ever collapse together.
    expect(kindOf(Klass)).not.toBe(kindOf(function named() {}));
  });

  it('reports a loss, a kind change and an addition as different events', () => {
    const document = (exports: { name: string; kind: string }[]) => ({
      $comment: 'irrelevant to the comparison',
      exports,
    });
    const base = document([
      { name: 'HistoryStore', kind: 'class' },
      { name: 'resolveConfig', kind: 'function' },
    ]);

    expect(describeValueSurfaceDrift(base, base)).toBeNull();

    const lost = describeValueSurfaceDrift(
      base,
      document([{ name: 'resolveConfig', kind: 'function' }])
    );
    expect(lost).toContain('LOST exports');
    expect(lost).toContain('GONE from the runtime surface (1): HistoryStore (class)');
    // The cause that leaves every other check in this repository green has to be named where the
    // reader is, or they will spend the investigation somewhere else.
    expect(lost).toContain('export type *');

    const rebound = describeValueSurfaceDrift(
      base,
      document([
        { name: 'HistoryStore', kind: 'object' },
        { name: 'resolveConfig', kind: 'function' },
      ])
    );
    expect(rebound).toContain('BOUND one or more to a different KIND');
    expect(rebound).toContain('KIND CHANGED (1): HistoryStore: class -> object');
    expect(rebound).not.toContain('LOST exports');

    const added = describeValueSurfaceDrift(
      base,
      document([...base.exports, { name: 'brandNew', kind: 'function' }])
    );
    expect(added).toContain('nothing was lost');
    expect(added).toContain('ADDED to the runtime surface (1): brandNew (function)');

    // A loss arriving alongside an addition must still lead with the loss: the careful branch is
    // the one that has to win, or a reader regenerates and blesses the removal.
    const both = describeValueSurfaceDrift(
      base,
      document([
        { name: 'resolveConfig', kind: 'function' },
        { name: 'brandNew', kind: 'function' },
      ])
    );
    expect(both).toContain('LOST exports');
    expect(both).toContain('GONE from the runtime surface (1): HistoryStore (class)');
    expect(both).toContain('ADDED to the runtime surface (1): brandNew (function)');
  });
});
