import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { HARDLINE_PATTERN_SURFACE } from '@gaunt-sloth/core/core/shell/hardline.js';

/**
 * EXT-112 — the §8 pattern surface, frozen, so a NARROWING of the shell floor cannot land silently.
 *
 * ## What this gate is for (read this before treating a red cell as a defect)
 *
 * It does not detect a bypass and it cannot. **It forces a DECLARATION.** A red cell here is the
 * moment the editor has to say what their edit removed, and the only way to green it is to edit the
 * literal below — a source change that shows up in the diff and has to be defended in review.
 *
 * The reason a declaration is needed at all is that nothing else in the repo can review a narrowing.
 * If an edit had removed a refusal that any spec asserts, that spec would be red — so a narrowing
 * that leaves the suite green has, by construction, a removal set that is entirely unasserted, which
 * is the same set as "uncovered". Green is structurally silent here, and an AI review of the diff is
 * no better: both read what the change still does, and the whole risk is in what it quietly stopped
 * doing. `hardline.ts`'s "How it may SHRINK" paragraph is the rule; this is its enforcement.
 *
 * ## Why an in-source literal and not `toMatchSnapshot()`
 *
 * A `.snap` file is regenerated by `vitest -u`. A gate whose entire purpose is to force a deliberate
 * declaration must not be satisfiable by a flag, so the expected surface is written out here as
 * ordinary source.
 *
 * ## What the gate provably CANNOT see
 *
 * It freezes strings. Floor behaviour is not only strings, so these narrowings move nothing here:
 *
 *  - **`normalizeCommand` is a FUNCTION** applied to the command before any pattern is tried. A
 *    narrowing implemented inside normalisation — dropping the fullwidth fold, or the backslash
 *    collapse — changes what the floor refuses without touching one frozen character.
 *  - **Control flow**: `isDeterministicExfiltration`'s per-pipeline split and its source-AND-sink
 *    conjunction, and the order `checkHardline` tries the arms. Dropping one of the two sink tests
 *    is a total narrowing of that arm and moves no string.
 *  - **A pattern built inside a function body** rather than bound at module scope would not be
 *    enumerated by the completeness check below, which reads module-scope bindings.
 *
 * Said plainly rather than left to a green run to overclaim: this gate covers the pattern surface,
 * not the floor.
 */

/**
 * The frozen surface — **the expected value, and the thing a narrowing has to edit.**
 *
 * Each value is the constant's verbatim source, with one presentation applied: where a member's
 * value contains another member's value, the inner one is written back as `${NAME}`. That is the
 * shape the module actually authors, and it is what makes the failure diff usable — an edit to
 * `CMD_POS` reddens `CMD_POS` alone instead of the twenty patterns built from it, so the cell names
 * the constant that moved rather than burying it.
 *
 * RegExps are recorded as `String(re)` — the `/…/flags` form — rather than `re.source`, because the
 * flags are part of the behaviour: a `g` flag makes `.test()` stateful across calls, which a
 * source-only record would not show.
 */
const EXPECTED_SURFACE: Readonly<Record<string, string | readonly string[]>> = {
  COMMAND_SEPARATOR_CLASS: ';&|\\n\\r',
  WRAPPER_FLAGS: '(?:-[^\\s]+\\s+)*',
  WRAPPER_ARMS: [
    'sudo\\s+(?:-[ugpUCDhRT]\\s+\\S+\\s+|-(?![ugpUCDhRT]\\s)[^\\s]+\\s+)*',
    'env\\s+(?:-u\\s+\\S+\\s+|-(?!u\\s)[^\\s]+\\s+)*(?:\\w+=\\S*\\s+)*',
    'timeout\\s+(?:-[sk]\\s+\\S+\\s+|-(?![sk]\\s)[^\\s]+\\s+)*[0-9]+(?:\\.[0-9]+)?[smhd]?\\s+',
    'nice\\s+(?:-n\\s+\\S+\\s+|-(?!n\\s)[^\\s]+\\s+)*',
    'ionice\\s+(?:-[cnp]\\s+\\S+\\s+|-(?![cnp]\\s)[^\\s]+\\s+)*',
    'stdbuf\\s+${WRAPPER_FLAGS}',
    '(?:eval|command|builtin|exec|nohup|setsid|time|xargs)\\s+${WRAPPER_FLAGS}',
  ],
  CMD_POS:
    '(?:^|[${COMMAND_SEPARATOR_CLASS}`]|\\$\\()\\s*(?:${WRAPPER_ARMS[0]}|${WRAPPER_ARMS[1]}|${WRAPPER_ARMS[2]}|${WRAPPER_ARMS[3]}|${WRAPPER_ARMS[4]}|${WRAPPER_ARMS[5]}|${WRAPPER_ARMS[6]})*\\s*',
  TARGET_TOKEN_END: '(?=$|[\\s)`${COMMAND_SEPARATOR_CLASS}])',
  H_SPACE: '[^\\S\\n\\r]+',
  H_TOKEN_EXCLUSIONS: '\\s`#${COMMAND_SEPARATOR_CLASS}',
  H_TOKEN_CHAR: '[^${H_TOKEN_EXCLUSIONS}]',
  H_OPERAND_CHAR: '[^${H_TOKEN_EXCLUSIONS}/]',
  ROOT_TARGET: '(?:"/\\s*(?:\\*|/)?"|\'/\\s*(?:\\*|/)?\'|/\\s*(?:\\*|/)?)${TARGET_TOKEN_END}',
  SYSTEM_DIR_TARGET:
    '(?:"(?:/(?:home|root|etc|usr|var|bin|sbin|boot|lib|lib64|opt|sys|proc))(?:/\\*?)?"|\'(?:/(?:home|root|etc|usr|var|bin|sbin|boot|lib|lib64|opt|sys|proc))(?:/\\*?)?\'|(?:/(?:home|root|etc|usr|var|bin|sbin|boot|lib|lib64|opt|sys|proc))(?:/\\*?)?)${TARGET_TOKEN_END}',
  RECURSIVE_FLAG: '(?:--recursive|-(?!-)${H_TOKEN_CHAR}*r${H_TOKEN_CHAR}*)',
  CHOWN_SKIPPABLE_ARG: '(?:-${H_TOKEN_CHAR}+|${H_OPERAND_CHAR}+)',
  CHOWN_HEAD:
    '${CMD_POS}chown${H_SPACE}(?:${CHOWN_SKIPPABLE_ARG}${H_SPACE})*${RECURSIVE_FLAG}${H_SPACE}(?:${CHOWN_SKIPPABLE_ARG}${H_SPACE})*',
  HARDLINE_PATTERNS: [
    '/${CMD_POS}rm\\s+(?:-[^\\s]*\\s+)*${ROOT_TARGET}/',
    '/${CMD_POS}rm\\s+(?:-[^\\s]*\\s+)*${SYSTEM_DIR_TARGET}/',
    '/${CMD_POS}rm\\s+(?:-[^\\s]*\\s+)*(?:~|\\$home)(?:\\/\\*)?${TARGET_TOKEN_END}/',
    '/${CMD_POS}mkfs(?:\\.[a-z0-9]+)?\\b/',
    '/${CMD_POS}dd\\b[^\\n]*\\bof=\\/dev\\/(?:sd|nvme|hd|mmcblk|vd|xvd)[a-z0-9]*/',
    '/>\\s*\\/dev\\/(?:sd|nvme|hd|mmcblk|vd|xvd)[a-z0-9]*\\b/',
    '/:\\s*\\(\\s*\\)\\s*\\{\\s*:\\s*\\|\\s*:\\s*&\\s*\\}\\s*;\\s*:/',
    '/${CMD_POS}chmod\\s+(?:-[^\\s]*\\s+)*${RECURSIVE_FLAG}\\s+(?:-[^\\s]*\\s+)*[0-7]{3,4}\\s+${ROOT_TARGET}/',
    '/${CMD_POS}chmod\\s+(?:-[^\\s]*\\s+)*${RECURSIVE_FLAG}\\s+(?:-[^\\s]*\\s+)*[0-7]{3,4}\\s+${SYSTEM_DIR_TARGET}/',
    '/${CHOWN_HEAD}${ROOT_TARGET}/',
    '/${CHOWN_HEAD}${SYSTEM_DIR_TARGET}/',
    '/${CMD_POS}kill\\s+(?:-[^\\s]+\\s+)+-1\\b/',
    '/${CMD_POS}(?:shutdown|reboot|halt|poweroff)\\b/',
    '/${CMD_POS}init\\s+[06]\\b/',
    '/${CMD_POS}systemctl\\s+(?:poweroff|reboot|halt|kexec)\\b/',
    '/${CMD_POS}telinit\\s+[06]\\b/',
  ],
  PIPELINE_SPLIT_RE: '/[;&\\n\\r]/',
  NETWORK_SINK_RE:
    '/${CMD_POS}(?:curl|wget|nc|ncat|netcat|telnet|socat|tftp|scp|sftp|aws\\s+s3|gsutil|gcloud\\s+storage)\\b/',
  RSYNC_REMOTE_TARGET: '(?!-)[^\\s/|]*:',
  RSYNC_REMOTE_SINK_RE: '/${CMD_POS}rsync\\b[^|]*\\s${RSYNC_REMOTE_TARGET}/',
  TOKEN_END: '/?(?=$|\\s)',
  NOT_PUBLIC_KEY: '(?![^\\s]*\\.pub\\b)',
  DOTENV_RE: '/(?<![\\w.\\-])\\.env(?:\\.[^\\s/]+)?(?=$|\\s)/',
  DOTENV_AS_OUTPUT_TARGET:
    '/(?:-o|--output|--output-document|>)[\\s=]*[^\\s]*\\.env(?:\\.[^\\s/]+)?(?=$|\\s)/',
  CREDENTIAL_SOURCE_PATTERNS: [
    '/\\.ssh\\/id_${NOT_PUBLIC_KEY}/',
    '/\\bid_(?:rsa|dsa|ecdsa|ed25519)\\b${NOT_PUBLIC_KEY}/',
    '/\\.ssh${TOKEN_END}/',
    '/\\.aws${TOKEN_END}/',
    '/\\.gnupg${TOKEN_END}/',
    '/\\.kube${TOKEN_END}/',
    '/\\.docker${TOKEN_END}/',
    '/\\.config\\/gcloud${TOKEN_END}/',
    '/\\.aws\\/credentials\\b/',
    '/\\.netrc\\b/',
    '/\\.npmrc\\b/',
    '/\\.docker\\/config\\.json\\b/',
    '/\\.kube\\/config\\b/',
    '/\\.gnupg\\//',
    '/\\.config\\/gcloud\\//',
    '/${CMD_POS}(?:printenv|env)\\s*(?=\\||$)/',
  ],
};

/**
 * The module-scope bindings `hardline.ts` introduces that are deliberately NOT in the surface, each
 * with the reason. **A binding is either enrolled or listed here** — the completeness check below is
 * an exact-set equality over the two, so a new pattern constant cannot be forgotten into the blind
 * spot.
 *
 * The criterion is not "constant vs function". It is whether the value is **baked in at module
 * load** — `quotedOrBare` is a builder and is fully captured, because its output is what
 * `ROOT_TARGET` and `SYSTEM_DIR_TARGET` hold — or **applied at runtime**, which is where the gate
 * goes blind.
 */
const NOT_A_PATTERN: Readonly<Record<string, string>> = {
  normalizeCommand:
    'Applied to the COMMAND at runtime, so a narrowing inside normalisation changes what the floor refuses without moving a frozen string. The gate\'s known blind spot; see "What the gate provably CANNOT see".',
  quotedOrBare:
    'A builder, not a runtime step: its output is baked into ROOT_TARGET and SYSTEM_DIR_TARGET at module load, so both spellings it produces are already frozen through those two members.',
  HARDLINE_PATTERN_SURFACE: 'The surface itself.',
  EXFILTRATION_ARM:
    'A diagnostic token reported as HardlineMatch.pattern for the arm that has no single regex. It is read by the debug archive and decides no refusal.',
  isDeterministicExfiltration:
    'Control flow — the per-pipeline split and the source-AND-sink conjunction. Invisible to a string snapshot.',
  checkHardline: 'Control flow — the order the arms are tried and what a match returns.',
  buildHardlineRefusal: 'The refusal wording shown to the user. It decides no refusal.',
};

/**
 * `hardline.ts`'s own source, for the completeness check — resolved RELATIVE TO THIS FILE via
 * `new URL(...)` + `fileURLToPath`, never from `process.cwd()` and never from a POSIX path literal,
 * which is what makes it a real path on win32 as well (the same rule `shellHardlineCorpus.spec.ts`
 * follows, and the failure mode that has turned this repo's Windows cell red before).
 *
 * This is the file the workspace vitest resolver also loads the module under test from. Nothing
 * asserts that directly — but the key-set check below compares the loaded module's surface against
 * declarations parsed out of THIS text, so a mismatch between the two files could not stay quiet.
 */
const HARDLINE_SOURCE = readFileSync(
  fileURLToPath(new URL('../../core/src/core/shell/hardline.ts', import.meta.url)),
  'utf8'
);

/**
 * Every name `hardline.ts` binds at module scope: its own top-level declarations (matched at column
 * zero, so nothing inside a docblock or a nested block is picked up) plus every value it imports.
 * `import type` is skipped — a type carries no runtime value and so cannot hold a pattern.
 */
function moduleScopeBindings(source: string): string[] {
  const names = new Set<string>();
  for (const match of source.matchAll(
    /^(?:export\s+)?(?:async\s+)?(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)/gm
  )) {
    names.add(match[1]);
  }
  for (const match of source.matchAll(/^import\s+(?!type\s)([\s\S]*?)\s+from\s+['"][^'"]+['"]/gm)) {
    for (const clause of match[1].replace(/[{}]/g, ' ').split(',')) {
      const local =
        clause
          .trim()
          .split(/\s+as\s+/)
          .pop()
          ?.trim() ?? '';
      if (/^[A-Za-z_$][\w$]*$/.test(local)) names.add(local);
    }
  }
  return [...names].sort();
}

/** Every leaf value in the live surface, keyed as `NAME` or `NAME[i]`, longest expansion first. */
function surfaceFragments(): Array<readonly [string, string]> {
  const fragments: Array<readonly [string, string]> = [];
  for (const [name, value] of Object.entries(HARDLINE_PATTERN_SURFACE)) {
    if (typeof value === 'string') fragments.push([name, value]);
    else value.forEach((element, index) => fragments.push([`${name}[${index}]`, element]));
  }
  return fragments.sort(
    ([nameA, a], [nameB, b]) => b.length - a.length || nameA.localeCompare(nameB)
  );
}

/**
 * Write every other member's value back as `${NAME}`, longest first so a composite (`CHOWN_HEAD`)
 * wins over the part it contains (`CMD_POS`). Each fragment is tried in its regex-source spelling
 * (`/` escaped, as `RegExp.prototype.source` writes it outside a character class) and then raw; a
 * spelling that does not occur verbatim simply does not substitute, so this can only shorten the
 * value, never invent one. Very short fragments are skipped as too weak to be meaningful.
 */
function render(key: string, value: string, fragments: Array<readonly [string, string]>): string {
  let out = value;
  for (const [name, expansion] of fragments) {
    if (name === key || expansion.length < 4) continue;
    const token = '${' + name + '}';
    const escaped = expansion.replaceAll('/', '\\/');
    if (escaped !== expansion) out = out.split(escaped).join(token);
    out = out.split(expansion).join(token);
  }
  return out;
}

/** The live surface in the same presentation as {@link EXPECTED_SURFACE}. */
function renderSurface(): Record<string, string | readonly string[]> {
  const fragments = surfaceFragments();
  const rendered: Record<string, string | readonly string[]> = {};
  for (const [name, value] of Object.entries(HARDLINE_PATTERN_SURFACE)) {
    rendered[name] =
      typeof value === 'string'
        ? render(name, value, fragments)
        : value.map((element, index) => render(`${name}[${index}]`, element, fragments));
  }
  return rendered;
}

/**
 * What someone hitting this cell at speed has to do, stated in the failure itself so they can act
 * without opening the node.
 */
const REQUIREMENT = [
  'A GREEN SUITE CANNOT REVIEW A NARROWING. If the edit had removed a refusal that any spec',
  'asserts, that spec would be red — so a green run proves only that everything the edit removed',
  'was unasserted, which is the same set as "uncovered".',
  '',
  'If this edit makes the floor refuse strictly FEWER commands — a new exclusion, a loosened',
  'bound, a tightened anchor, a narrower character class — it ships with its REMOVAL SET: the',
  'commands that matched before and do not match after, characterised from the shape of the edit',
  '(never sampled from the corpus, which sees only its own cases), plus probes pinned at the',
  'dangerous end of that set. Derive it as the reviewer, independently of the author.',
  '',
  'CHECK WHICH HALF YOU EDITED. For the destructive-verb arms a miss still has the confirmation',
  'dialog and the rater behind it. For the exfiltration arms removing a refusal IS the harm, so',
  '"strictly subtractive — it can only remove refusals" is a safety property in the first half and',
  'a description of the vulnerability in the second.',
  '',
  'Then update EXPECTED_SURFACE in this file, in the same commit. That edit is the declaration.',
].join('\n');

describe('the §8 hardline pattern surface is frozen (EXT-112)', () => {
  it('reads hardline.ts itself, so a wrong path or a parse that matches nothing fails loudly rather than passing vacuously', () => {
    expect(HARDLINE_SOURCE).toContain('@module core/shell/hardline');
    const bindings = moduleScopeBindings(HARDLINE_SOURCE);
    expect(bindings.length).toBeGreaterThan(20);
    expect(bindings).toContain('CMD_POS');
    // The imported member — the writer audit this surface exists to carry, since a change to it
    // lands in another module entirely.
    expect(bindings).toContain('COMMAND_SEPARATOR_CLASS');
    expect(Object.keys(HARDLINE_PATTERN_SURFACE)).toContain('COMMAND_SEPARATOR_CLASS');
  });

  it('matches the declared surface — every pattern string, verbatim', () => {
    const actual = renderSurface();
    const names = [...new Set([...Object.keys(EXPECTED_SURFACE), ...Object.keys(actual)])] as const;
    const moved = names.filter(
      (name) => JSON.stringify(actual[name]) !== JSON.stringify(EXPECTED_SURFACE[name])
    );

    const detail = moved
      .map(
        (name) =>
          `  ${name}\n    frozen:  ${JSON.stringify(EXPECTED_SURFACE[name] ?? null)}\n    current: ${JSON.stringify(actual[name] ?? null)}`
      )
      .join('\n');

    expect(
      moved,
      `The §8 hardline pattern surface has MOVED: ${moved.join(', ')}\n\n${detail}\n\n${REQUIREMENT}`
    ).toEqual([]);
    // Belt and braces: the same comparison as a whole-object diff, for the vitest output.
    expect(actual).toEqual(EXPECTED_SURFACE);
  });

  it('enrols every module-scope binding hardline.ts has, so a new pattern constant cannot be forgotten', () => {
    const bindings = moduleScopeBindings(HARDLINE_SOURCE);
    const accounted = [
      ...Object.keys(HARDLINE_PATTERN_SURFACE),
      ...Object.keys(NOT_A_PATTERN),
    ].sort();
    const unenrolled = bindings.filter((name) => !accounted.includes(name));

    expect(
      bindings,
      `hardline.ts binds ${unenrolled.join(', ') || '(nothing new)'} at module scope with no place in the surface.\n\n` +
        'Every module-scope binding is either a member of HARDLINE_PATTERN_SURFACE — which is what makes a\n' +
        'narrowing of it loud — or an entry in NOT_A_PATTERN carrying the reason it decides no refusal.\n' +
        'A binding in neither is a pattern this gate is blind to.\n\n' +
        REQUIREMENT
    ).toEqual(accounted);
  });

  it('keeps no stale NOT_A_PATTERN entry after a rename or a deletion', () => {
    const bindings = moduleScopeBindings(HARDLINE_SOURCE);
    for (const name of Object.keys(NOT_A_PATTERN)) {
      expect(bindings, `${name} is no longer a binding in hardline.ts`).toContain(name);
    }
  });
});
