name: Integration tests platforms

on:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ${{ matrix.os }}
    environment: integration tests
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        # only test macOS and Windows, linux is tested in all other variations
        os: [macos-latest, windows-latest]
        node-version: [24.x, latest]
        provider: [openrouter]
      max-parallel: 4

    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Enable Corepack
      run: corepack enable

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run lite integration tests with ${{ matrix.provider }}
      run: pnpm run it ${{ matrix.provider }} simple
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        INCEPTION_API_KEY: ${{ secrets.INCEPTION_API_KEY }}
        OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
