name: Integration tests

on:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: integration tests
    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v6

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 11.3.0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run Integration
      run: pnpm run it $BIG_TEST_PROVIDER
      env:
        BIG_TEST_PROVIDER: ${{ vars.BIG_TEST_PROVIDER }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
