name: Tests and Lint

on:
  workflow_dispatch:

jobs:
  test-and-lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v7
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Enable Corepack
      run: corepack enable

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run ESLint
      run: pnpm run lint

    - name: Run Tests
      run: pnpm test

  test-platforms:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [24.x, latest]
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Tests
        run: pnpm test
